services:
  trmnl:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: ["./docker-entrypoint.sh"]
    restart: unless-stopped

  server:
    build: .
    volumes:
      - ./data:/app/data
    working_dir: /app/data
    command: ["python3", "simple-cors-http-server.py", "8000"]
    ports:
      - "8000:8000"
    restart: unless-stopped
